Many Machine Learning problems involve thousands or even millions of features for
each training instance. Not only does this make training extremely slow, it can also
make it much harder to find a good solution, as we will see. This problem is often
referred to as the curse of dimensionality.


Projection


In most real-world problems, training instances are not spread out uniformly across
all dimensions. Many features are almost constant, while others are highly correlated. As a result, all training instances actually lie within
(or close to) a much lower-dimensional subspace of the high-dimensional space.

Manifold learning

Principal Component Analysis (PCA)

Principal Component Analysis (PCA) is by far the most popular dimensionality reduc‐
tion algorithm. First it identifies the hyperplane that lies closest to the data, and then
it projects the data onto it.

The following Python code uses NumPy’s svd() function to obtain all the principal
components of the training set, then extracts the first two PCs:

In [1]:
import numpy as np

X = np.c_[np.random.rand(100,1) , np.random.rand(100,1)]

X_centered = X - X.mean(axis = 0)
U, s, Vt = np.linalg.svd(X_centered)

c1 = Vt.T[:,0]
c2 = Vt.T[:,1]

In [2]:
X

array([[0.34457663, 0.01834936],
       [0.09023821, 0.44398031],
       [0.9273829 , 0.98688835],
       [0.48251468, 0.06117208],
       [0.68679591, 0.50299676],
       [0.99626179, 0.95690896],
       [0.42806608, 0.43563099],
       [0.54597902, 0.15407898],
       [0.23773758, 0.71266296],
       [0.52251402, 0.14559509],
       [0.1316356 , 0.81012166],
       [0.72580402, 0.41339155],
       [0.65072862, 0.88952478],
       [0.07748383, 0.18572569],
       [0.60615776, 0.58656574],
       [0.81308415, 0.84238288],
       [0.83051295, 0.41322916],
       [0.5201142 , 0.97670506],
       [0.62759524, 0.47671673],
       [0.26489945, 0.43142482],
       [0.68689344, 0.12153395],
       [0.73190803, 0.01916767],
       [0.84045065, 0.04037851],
       [0.94363424, 0.42618515],
       [0.98109954, 0.01105289],
       [0.11439797, 0.90336701],
       [0.91089991, 0.17886533],
       [0.42959948, 0.72034485],
       [0.88016668, 0.16213488],
       [0.94722802, 0.35763611],
       [0.

In [3]:
Vt

array([[ 0.36235066, -0.93204184],
       [-0.93204184, -0.36235066]])

In [4]:
c2

array([-0.93204184, -0.36235066])

In [5]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
pca.fit_transform(X)

array([[-0.3429226 , -0.37207463],
       [ 0.14594295, -0.45490102],
       [ 0.34861603,  0.52207596],
       [-0.35299197, -0.22799375],
       [-0.01521432,  0.12250037],
       [ 0.29571567,  0.57541091],
       [ 0.01574888, -0.14305669],
       [-0.2893952 , -0.13517745],
       [ 0.34291993, -0.2200681 ],
       [-0.28879999, -0.16012196],
       [ 0.47220164, -0.28364536],
       [-0.11286474,  0.12638906],
       [ 0.35811497,  0.22894283],
       [-0.09013961, -0.56036737],
       [ 0.09189475,  0.07762351],
       [ 0.25534711,  0.36318308],
       [-0.15095745,  0.22392331],
       [ 0.48669886,  0.13879456],
       [-0.01825702,  0.05780028],
       [ 0.07095209, -0.29665892],
       [-0.37078897, -0.01563203],
       [-0.48250969, -0.01076903],
       [-0.50207079,  0.09808299],
       [-0.1798715 ,  0.3340517 ],
       [-0.58036771,  0.21854748],
       [ 0.56535627, -0.26592403],
       [-0.39852262,  0.21392544],
       [ 0.28055848, -0.03846124],
       [-0.40297989,

In [6]:
pca.explained_variance_ratio_

array([0.52752571, 0.47247429])