Operations with Tensor

In [1]:
import tensorflow as tf

In [4]:
t = tf.constant([[1,2,3],[4,5,6]]) #vector

In [5]:
tf.constant(42) #Scaler

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [8]:
t @ tf.transpose(t)        #Or use tf.matmul()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [17]:
tf.squeeze(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [16]:
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [19]:
t = tf.constant([[[1, 2, 3]]])  
print(t.shape)  # (1, 1, 3)

print(tf.squeeze(t))

(1, 1, 3)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [20]:
t = tf.constant([[[1, 2, 3]]])

t_squeezed = tf.squeeze(t)

print(t.shape)           # (1, 1, 3)
print(t_squeezed.shape)  # (3,)

(1, 1, 3)
(3,)


Tensors and Numpy

In [24]:
import numpy as np
a = np.array([2,4,5])
t = tf.constant(a)

In [25]:
t.numpy()

array([2, 4, 5])

Type Conversion

In [29]:
tf.constant(2.) + tf.constant(42.)

<tf.Tensor: shape=(), dtype=float32, numpy=44.0>

In [30]:
t2 = tf.constant(40, dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2,tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

Variables

In [32]:
v= tf.Variable([[1,2,3],[4,5,6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [33]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [34]:
v[0,1].assign(40)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2, 40,  6],
       [ 8, 10, 12]], dtype=int32)>

<big>Customizing Models and Training Algorithms

Custom Loss Function

Huber Loss

In [38]:
def create_huber(threshold=1.0):
 def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < threshold
    squared_loss = tf.square(error) / 2
    linear_loss = threshold * tf.abs(error) - threshold**2 / 2
    return tf.where(is_small_error, squared_loss, linear_loss)
    return huber_fn


saving and Loading Models that contains Custom Components

model = keras.models.load_model("my_custom_model.h5",custom_objects={"huber_fn":create_huber(2.0)})

Custom Activation Function, Initializers, Regularizers and Constraints

Custom Metrics

Just reading these parts

I don't think I need to write custom functions for now, so I will look at this part in future